version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - ./:/app
    ports:
      - "80:80"
    env_file:
      - .env
  db:
    image: postgres:16-bookworm
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shorterner_service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
